site:
  name: AstroWind
  site: 'https://astrowind.vercel.app'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

# Metadatos SEO por defecto
metadata:
  title:
    default: AstroWind
    template: '%s — AstroWind'
  description: "\U0001F680 Adecuado para Startups, Pequeñas Empresas, Sitios Web de Sass, Portafolios Profesionales, Sitios Web de Marketing, Páginas de Destino y Blogs."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: AstroWind
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@onwidget'
    site: '@onwidget'
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' # Ruta principal del blog, puedes cambiar esto a "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category' # Ruta principal de la categoría /category/some-category, puedes cambiar esto a "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag' # Ruta principal de la etiqueta /tag/some-tag, puedes cambiar esto a "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # o "G-XXXXXXXXXX"

ui:
  theme: 'system' # Valores: "system" | "light" | "dark" | "light:only" | "dark:only"
